#!/bin/sh
if [ -z "$1" ]
  then session="tomi"
else
  session=$1
fi

tmux start-server

tmux new-session -A -s $session -d
tmux source-file /home/tomi/.tmux.conf

tmux split-window -h -p 35
tmux split-window -v
tmux selectp -t 0


tmux attach-session -d
